name: todo_list
description: "App that makes everydays duties easier due to the fact planning"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  shared_preferences:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0

  # Google Sign-In
  google_sign_in: ^6.1.5

  # Localisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Storage
  path_provider: ^2.0.15
  shared_preferences: ^2.3.2   # ← version added

  # Utilities
  uuid: ^4.2.1

  # QR / scanner for group invites
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
